services:
  dashboard:
    # Override pour Raspberry Pi 
    network_mode: host

    ports: !reset []
    
    volumes:
      - /tmp/shairport-sync-metadata:/tmp/shairport-sync-metadata
      - /run/log/journal:/run/log/journal:ro
      - /var/log/journal:/var/log/journal:ro

    devices:
      - /dev/snd:/dev/snd

    group_add:
      - audio
      - systemd-journal
